name: Build
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.3.1
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn build
